version: '3.8'
services:
  vpn-api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - PORT=8080
    env_file:
      - .env
    ports:
      - "8080:8080"
    restart: always
    volumes:
      # - ./scripts:/scripts
      - /var/run/docker.sock:/var/run/docker.sock
