version: '3.8'
services:
  vpn-api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - PORT=5000
    ports:
      - "5000:5000"
    restart: always
    volumes:
      - ./scripts:/scripts
